from enum import StrEnum


class Currency(StrEnum):
    AUSTRALIAN_DOLLAR = "Австралийский доллар"
    AZERBAIJANI_MANAT = "Азербайджанский манат"
    BRITISH_POUND = "Фунт стерлингов Соединенного королевства"
    ARMENIAN_DRAM = "Армянских драмов"
    BELARUSIAN_RUBLE = "Белорусский рубль"
    BULGARIAN_LEV = "Болгарский лев"
    BRAZILIAN_REAL = "Бразильский реал"
    HUNGARIAN_FORINT = "Венгерских форинтов"
    VIETNAMESE_DONG = "Вьетнамских донгов"
    HONG_KONG_DOLLAR = "Гонконгский доллар"
    GEORGIAN_LARI = "Грузинский лари"
    DANISH_KRONE = "Датская крона"
    UAE_DIRHAM = "Дирхам ОАЭ"
    USD = "Доллар США"
    EURO = "Евро"
    EGYPTIAN_POUND = "Египетских фунтов"
    INDIAN_RUPEE = "Индийских рупий"
    INDONESIAN_RUPIAH = "Индонезийских рупий"
    KAZAKHSTANI_TENGE = "Казахстанских тенге"
    CANADIAN_DOLLAR = "Канадский доллар"
    QATARI_RIYAL = "Катарский риал"
    KYRGYZ_SOM = "Киргизских сомов"
    CHINESE_YUAN = "Китайский юань"
    MOLDOVAN_LEU = "Молдавских леев"
    NEW_ZEALAND_DOLLAR = "Новозеландский доллар"
    NORWEGIAN_KRONE = "Норвежских крон"
    POLISH_ZLOTY = "Польский злотый"
    ROMANIAN_LEU = "Румынский лей"
    SDR = "СДР (специальные права заимствования)"
    SINGAPORE_DOLLAR = "Сингапурский доллар"
    TAJIKISTANI_SOMONI = "Таджикских сомони"
    THAI_BAHT = "Таиландских батов"
    TURKISH_LIRA = "Турецких лир"
    NEW_TURKMENISTANI_MANAT = "Новый туркменский манат"
    UZBEKISTANI_SUM = "Узбекских сумов"
    UKRAINIAN_HRYVNIA = "Украинских гривен"
    CZECH_KORUNA = "Чешских крон"
    SWEDISH_KRONA = "Шведских крон"
    SWISS_FRANC = "Швейцарский франк"
    SERBIAN_DINAR = "Сербских динаров"
    SOUTH_AFRICAN_RAND = "Южноафриканских рэндов"
    SOUTH_KOREAN_WON = "Вон Республики Корея"
    JAPANESE_YEN = "Японских иен"
