apiVersion: v1
kind: Service
metadata:
   name: api

spec:
  type: LoadBalancer
  selector:
    app: redbl4e

  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000

---
apiVersion: v1
kind: Service
metadata:
  name: redis

spec:
  type: LoadBalancer
  selector:
    app: redbl4e
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq

spec:
  type: LoadBalancer
  selector:
    app: redbl4e
  ports:
   - protocol: TCP
     port: 5672
     targetPort: 5672
     name: amqp
   - protocol: TCP
     port: 15672
     targetPort: 15672
     name: management